media:
  input: public/images
  output: /images

content:
  - name: peppers
    label: Pepper Varieties
    type: collection
    path: src/content/peppers
    filename: "{primary}.md"

    view:
      fields:
        - name
        - species
        - heat
        - available

    fields:
      - name: name
        label: Name
        type: string
        required: true

      - name: species
        label: Species
        type: string
        required: true

      - name: heat
        label: Heat
        type: string
        required: true

      - name: color
        label: Color
        type: string

      - name: description
        label: Short Description
        type: text
        required: true

      - name: image
        label: Main Photo
        type: image

      - name: gallery
        label: Gallery
        type: object
        list: true
        fields:
          - name: image
            label: Image
            type: image

          - name: caption
            label: Caption
            type: string

      - name: available
        label: Available
        type: boolean
        default: false

      - name: seedPrice
        label: Seed Price
        type: number

      - name: seedQuantity
        label: Seeds Per Pack
        type: string

      - name: purchaseUrl
        label: Purchase Link
        type: string